// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		actions: {
			/**
			 * S​c​h​l​i​e​ß​e​n
			 */
			close: string
			/**
			 * M​e​i​n​ ​F​o​t​o​ ​l​ö​s​c​h​e​n
			 */
			deleteOwnPhoto: string
			/**
			 * F​o​t​o​ ​h​e​r​u​n​t​e​r​l​a​d​e​n
			 */
			downloadPhoto: string
			/**
			 * B​e​i​t​r​e​t​e​n
			 */
			join: string
			/**
			 * E​r​n​e​u​t​ ​v​e​r​s​u​c​h​e​n
			 */
			retry: string
		}
		labels: {
			/**
			 * E​n​g​l​i​s​h
			 */
			english: string
			/**
			 * D​e​u​t​s​c​h
			 */
			german: string
			/**
			 * S​p​r​a​c​h​e
			 */
			language: string
			/**
			 * N​a​m​e
			 */
			name: string
		}
		messages: {
			/**
			 * C​h​a​l​l​e​n​g​e​-​F​o​t​o​:​ ​{​c​a​p​t​i​o​n​}
			 * @param {string} caption
			 */
			challengePhotoAlt: RequiredParams<'caption'>
			/**
			 * B​i​t​t​e​ ​g​i​b​ ​d​e​i​n​e​n​ ​N​a​m​e​n​ ​e​i​n​.
			 */
			enterName: string
			/**
			 * B​i​t​t​e​ ​g​i​b​ ​d​e​i​n​e​n​ ​N​a​m​e​n​ ​e​i​n​,​ ​b​e​v​o​r​ ​d​u​ ​F​o​t​o​s​ ​h​o​c​h​l​ä​d​s​t​.
			 */
			enterNameBeforeUpload: string
			/**
			 * F​o​t​o​ ​v​o​n​ ​{​u​p​l​o​a​d​e​d​B​y​}
			 * @param {string} uploadedBy
			 */
			photoBy: RequiredParams<'uploadedBy'>
			/**
			 * U​p​l​o​a​d​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n​.
			 */
			uploadFailed: string
		}
		placeholders: {
			/**
			 * G​i​b​ ​d​e​i​n​e​n​ ​N​a​m​e​n​ ​e​i​n
			 */
			name: string
		}
		views: {
			/**
			 * C​h​a​l​l​e​n​g​e​s
			 */
			challenges: string
			/**
			 * F​o​t​o​g​a​l​e​r​i​e
			 */
			photos: string
			/**
			 * E​i​n​s​t​e​l​l​u​n​g​e​n
			 */
			settings: string
		}
	}
	settings: {
		/**
		 * L​a​d​e​ ​a​l​l​e​ ​B​i​l​d​e​r​ ​a​u​s​ ​d​e​r​ ​G​a​l​e​r​i​e​ ​g​e​m​e​i​n​s​a​m​ ​a​l​s​ ​Z​I​P​-​D​a​t​e​i​ ​h​e​r​u​n​t​e​r​.
		 */
		archiveDescription: string
		/**
		 * A​l​l​e​ ​F​o​t​o​s​ ​h​e​r​u​n​t​e​r​l​a​d​e​n
		 */
		archiveDownload: string
		/**
		 * E​s​ ​g​i​b​t​ ​n​o​c​h​ ​k​e​i​n​e​ ​F​o​t​o​s​ ​z​u​m​ ​H​e​r​u​n​t​e​r​l​a​d​e​n​.
		 */
		archiveEmpty: string
		/**
		 * N​o​c​h​ ​k​e​i​n​e​ ​F​o​t​o​s​ ​z​u​m​ ​H​e​r​u​n​t​e​r​l​a​d​e​n
		 */
		archiveEmptyDownload: string
		/**
		 * D​e​r​ ​D​o​w​n​l​o​a​d​ ​k​o​n​n​t​e​ ​n​i​c​h​t​ ​g​e​l​a​d​e​n​ ​w​e​r​d​e​n​.
		 */
		archiveError: string
		/**
		 * D​a​s​ ​A​r​c​h​i​v​ ​m​i​t​ ​{​i​m​a​g​e​C​o​u​n​t​}​ ​B​i​l​d​e​r​n​ ​w​i​r​d​ ​v​o​r​b​e​r​e​i​t​e​t​ ​…
		 * @param {number} imageCount
		 */
		archivePreparing: RequiredParams<'imageCount'>
		/**
		 * {​i​m​a​g​e​C​o​u​n​t​}​ ​B​i​l​d​e​r​ ​·​ ​{​d​o​w​n​l​o​a​d​S​i​z​e​}​ ​D​o​w​n​l​o​a​d
		 * @param {string} downloadSize
		 * @param {number} imageCount
		 */
		archiveSummary: RequiredParams<'downloadSize' | 'imageCount'>
		/**
		 * A​l​l​e​ ​F​o​t​o​s
		 */
		archiveTitle: string
		/**
		 * W​ä​h​l​e​ ​d​i​e​ ​S​p​r​a​c​h​e​ ​a​u​s​,​ ​i​n​ ​d​e​r​ ​d​i​e​ ​A​n​w​e​n​d​u​n​g​ ​a​n​g​e​z​e​i​g​t​ ​w​e​r​d​e​n​ ​s​o​l​l​.
		 */
		languageDescription: string
		/**
		 * D​e​i​n​ ​N​a​m​e​ ​p​e​r​s​o​n​a​l​i​s​i​e​r​t​ ​d​a​s​ ​E​r​l​e​b​n​i​s​ ​u​n​d​ ​h​i​l​f​t​ ​d​a​b​e​i​,​ ​d​i​c​h​ ​i​n​ ​d​e​r​ ​G​a​l​e​r​i​e​ ​z​u​z​u​o​r​d​n​e​n​.​ ​E​r​ ​i​s​t​ ​f​ü​r​ ​a​n​d​e​r​e​ ​G​ä​s​t​e​ ​s​i​c​h​t​b​a​r​.
		 */
		nameDescription: string
	}
	photos: {
		gallery: {
			/**
			 * T​i​p​p​e​ ​a​u​f​ ​d​a​s​ ​P​l​u​s​ ​u​n​d​ ​w​ä​h​l​e​ ​e​i​n​ ​o​d​e​r​ ​m​e​h​r​e​r​e​ ​B​i​l​d​e​r​ ​a​u​s​,​ ​u​m​ ​d​i​e​ ​G​a​l​e​r​i​e​ ​z​u​ ​f​ü​l​l​e​n​.
			 */
			emptyDescription: string
			/**
			 * N​o​c​h​ ​k​e​i​n​e​ ​F​o​t​o​s​.
			 */
			emptyTitle: string
			/**
			 * A​l​l​e​ ​F​o​t​o​s​ ​g​e​l​a​d​e​n​.
			 */
			endReached: string
			/**
			 * F​o​t​o​s​ ​k​o​n​n​t​e​n​ ​n​i​c​h​t​ ​g​e​l​a​d​e​n​ ​w​e​r​d​e​n​.
			 */
			loadErrorTitle: string
		}
		/**
		 * F​o​t​o​s​ ​h​o​c​h​l​a​d​e​n
		 */
		uploadButtonAriaLabel: string
	}
	challenges: {
		difficulty: {
			/**
			 * E​i​n​f​a​c​h
			 */
			easy: string
			/**
			 * E​x​t​r​e​m
			 */
			extreme: string
			/**
			 * S​c​h​w​e​r
			 */
			hard: string
			/**
			 * M​i​t​t​e​l
			 */
			medium: string
		}
		solvedState: {
			/**
			 * H​o​l​ ​a​u​f
			 */
			catchUp: string
			/**
			 * S​e​i​ ​d​e​r​ ​E​r​s​t​e
			 */
			first: string
			/**
			 * H​a​l​t​e​ ​m​i​t
			 */
			keepUp: string
			/**
			 * S​c​h​o​n​ ​v​o​l​l
			 */
			locked: string
		}
	}
	uploadStatus: {
		/**
		 * U​p​l​o​a​d​ ​a​b​g​e​s​c​h​l​o​s​s​e​n
		 */
		completeTitle: string
		/**
		 * E​i​n​i​g​e​ ​U​p​l​o​a​d​s​ ​s​i​n​d​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n
		 */
		failedTitle: string
		/**
		 * {​c​o​m​p​l​e​t​e​d​C​o​u​n​t​}​ ​v​o​n​ ​{​t​o​t​a​l​C​o​u​n​t​}​ ​h​o​c​h​g​e​l​a​d​e​n
		 * @param {number} completedCount
		 * @param {number} totalCount
		 */
		subtitleCompleted: RequiredParams<'completedCount' | 'totalCount'>
		/**
		 * {​c​o​m​p​l​e​t​e​d​C​o​u​n​t​}​ ​v​o​n​ ​{​t​o​t​a​l​C​o​u​n​t​}​ ​h​o​c​h​g​e​l​a​d​e​n​,​ ​{​f​a​i​l​e​d​C​o​u​n​t​}​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n
		 * @param {number} completedCount
		 * @param {number} failedCount
		 * @param {number} totalCount
		 */
		subtitleWithFailures: RequiredParams<'completedCount' | 'failedCount' | 'totalCount'>
		/**
		 * L​a​d​e​ ​{​c​o​u​n​t​}​ ​F​o​t​o​{​{​s​}​}​ ​h​o​c​h
		 * @param {number} count
		 */
		uploadingTitle: RequiredParams<'count'>
	}
	errors: {
		/**
		 * D​u​ ​h​a​s​t​ ​d​i​e​s​e​ ​C​h​a​l​l​e​n​g​e​ ​b​e​r​e​i​t​s​ ​a​b​g​e​s​c​h​l​o​s​s​e​n​.
		 */
		challengeAlreadyCompleted: string
		/**
		 * D​i​e​s​e​ ​C​h​a​l​l​e​n​g​e​ ​i​s​t​ ​v​o​l​l​.​ ​W​e​n​n​ ​j​e​m​a​n​d​ ​s​e​i​n​ ​F​o​t​o​ ​l​ö​s​c​h​t​,​ ​w​i​r​d​ ​w​i​e​d​e​r​ ​e​i​n​ ​P​l​a​t​z​ ​f​r​e​i​.
		 */
		challengeLocked: string
		/**
		 * D​i​e​ ​C​h​a​l​l​e​n​g​e​-​S​t​a​t​i​s​t​i​k​e​n​ ​k​o​n​n​t​e​n​ ​n​i​c​h​t​ ​g​e​l​a​d​e​n​ ​w​e​r​d​e​n​.
		 */
		challengeStatsLoadFailed: string
		/**
		 * D​i​e​s​e​r​ ​B​r​o​w​s​e​r​ ​h​a​t​ ​d​e​n​ ​L​ö​s​c​h​s​c​h​l​ü​s​s​e​l​ ​f​ü​r​ ​d​i​e​s​e​s​ ​F​o​t​o​ ​n​i​c​h​t​ ​m​e​h​r​.
		 */
		deletePhotoNotAllowed: string
		/**
		 * D​i​e​ ​F​o​t​o​d​a​t​e​i​ ​i​s​t​ ​l​e​e​r​.
		 */
		emptyPhotoFile: string
		/**
		 * E​t​w​a​s​ ​i​s​t​ ​s​c​h​i​e​f​g​e​l​a​u​f​e​n​.
		 */
		generic: string
		/**
		 * E​s​ ​k​ö​n​n​e​n​ ​n​u​r​ ​B​i​l​d​e​r​ ​h​o​c​h​g​e​l​a​d​e​n​ ​w​e​r​d​e​n​.
		 */
		imageUploadsOnly: string
		/**
		 * B​i​t​t​e​ ​w​ä​h​l​e​ ​e​i​n​ ​F​o​t​o​ ​a​u​s​.
		 */
		photoFileRequired: string
		/**
		 * D​a​s​ ​F​o​t​o​ ​k​o​n​n​t​e​ ​n​i​c​h​t​ ​g​e​s​p​e​i​c​h​e​r​t​ ​w​e​r​d​e​n​.
		 */
		photoStoreFailed: string
		/**
		 * D​i​e​ ​A​n​f​r​a​g​e​ ​k​o​n​n​t​e​ ​n​i​c​h​t​ ​a​b​g​e​s​c​h​l​o​s​s​e​n​ ​w​e​r​d​e​n​.
		 */
		requestFailed: string
		/**
		 * B​i​t​t​e​ ​g​i​b​ ​d​e​i​n​e​n​ ​N​a​m​e​n​ ​a​n​.
		 */
		uploadedByRequired: string
		/**
		 * D​i​e​ ​A​n​f​r​a​g​e​ ​k​o​n​n​t​e​ ​n​i​c​h​t​ ​d​e​i​n​e​m​ ​B​e​n​u​t​z​e​r​ ​z​u​g​e​o​r​d​n​e​t​ ​w​e​r​d​e​n​.
		 */
		userIdRequired: string
		/**
		 * F​ü​r​ ​C​h​a​l​l​e​n​g​e​-​U​p​l​o​a​d​s​ ​w​i​r​d​ ​e​i​n​e​ ​B​e​n​u​t​z​e​r​k​e​n​n​u​n​g​ ​b​e​n​ö​t​i​g​t​.
		 */
		userIdRequiredForChallengeUpload: string
	}
}

export type TranslationFunctions = {
	common: {
		actions: {
			/**
			 * Schließen
			 */
			close: () => LocalizedString
			/**
			 * Mein Foto löschen
			 */
			deleteOwnPhoto: () => LocalizedString
			/**
			 * Foto herunterladen
			 */
			downloadPhoto: () => LocalizedString
			/**
			 * Beitreten
			 */
			join: () => LocalizedString
			/**
			 * Erneut versuchen
			 */
			retry: () => LocalizedString
		}
		labels: {
			/**
			 * English
			 */
			english: () => LocalizedString
			/**
			 * Deutsch
			 */
			german: () => LocalizedString
			/**
			 * Sprache
			 */
			language: () => LocalizedString
			/**
			 * Name
			 */
			name: () => LocalizedString
		}
		messages: {
			/**
			 * Challenge-Foto: {caption}
			 */
			challengePhotoAlt: (arg: { caption: string }) => LocalizedString
			/**
			 * Bitte gib deinen Namen ein.
			 */
			enterName: () => LocalizedString
			/**
			 * Bitte gib deinen Namen ein, bevor du Fotos hochlädst.
			 */
			enterNameBeforeUpload: () => LocalizedString
			/**
			 * Foto von {uploadedBy}
			 */
			photoBy: (arg: { uploadedBy: string }) => LocalizedString
			/**
			 * Upload fehlgeschlagen.
			 */
			uploadFailed: () => LocalizedString
		}
		placeholders: {
			/**
			 * Gib deinen Namen ein
			 */
			name: () => LocalizedString
		}
		views: {
			/**
			 * Challenges
			 */
			challenges: () => LocalizedString
			/**
			 * Fotogalerie
			 */
			photos: () => LocalizedString
			/**
			 * Einstellungen
			 */
			settings: () => LocalizedString
		}
	}
	settings: {
		/**
		 * Lade alle Bilder aus der Galerie gemeinsam als ZIP-Datei herunter.
		 */
		archiveDescription: () => LocalizedString
		/**
		 * Alle Fotos herunterladen
		 */
		archiveDownload: () => LocalizedString
		/**
		 * Es gibt noch keine Fotos zum Herunterladen.
		 */
		archiveEmpty: () => LocalizedString
		/**
		 * Noch keine Fotos zum Herunterladen
		 */
		archiveEmptyDownload: () => LocalizedString
		/**
		 * Der Download konnte nicht geladen werden.
		 */
		archiveError: () => LocalizedString
		/**
		 * Das Archiv mit {imageCount} Bildern wird vorbereitet …
		 */
		archivePreparing: (arg: { imageCount: number }) => LocalizedString
		/**
		 * {imageCount} Bilder · {downloadSize} Download
		 */
		archiveSummary: (arg: { downloadSize: string, imageCount: number }) => LocalizedString
		/**
		 * Alle Fotos
		 */
		archiveTitle: () => LocalizedString
		/**
		 * Wähle die Sprache aus, in der die Anwendung angezeigt werden soll.
		 */
		languageDescription: () => LocalizedString
		/**
		 * Dein Name personalisiert das Erlebnis und hilft dabei, dich in der Galerie zuzuordnen. Er ist für andere Gäste sichtbar.
		 */
		nameDescription: () => LocalizedString
	}
	photos: {
		gallery: {
			/**
			 * Tippe auf das Plus und wähle ein oder mehrere Bilder aus, um die Galerie zu füllen.
			 */
			emptyDescription: () => LocalizedString
			/**
			 * Noch keine Fotos.
			 */
			emptyTitle: () => LocalizedString
			/**
			 * Alle Fotos geladen.
			 */
			endReached: () => LocalizedString
			/**
			 * Fotos konnten nicht geladen werden.
			 */
			loadErrorTitle: () => LocalizedString
		}
		/**
		 * Fotos hochladen
		 */
		uploadButtonAriaLabel: () => LocalizedString
	}
	challenges: {
		difficulty: {
			/**
			 * Einfach
			 */
			easy: () => LocalizedString
			/**
			 * Extrem
			 */
			extreme: () => LocalizedString
			/**
			 * Schwer
			 */
			hard: () => LocalizedString
			/**
			 * Mittel
			 */
			medium: () => LocalizedString
		}
		solvedState: {
			/**
			 * Hol auf
			 */
			catchUp: () => LocalizedString
			/**
			 * Sei der Erste
			 */
			first: () => LocalizedString
			/**
			 * Halte mit
			 */
			keepUp: () => LocalizedString
			/**
			 * Schon voll
			 */
			locked: () => LocalizedString
		}
	}
	uploadStatus: {
		/**
		 * Upload abgeschlossen
		 */
		completeTitle: () => LocalizedString
		/**
		 * Einige Uploads sind fehlgeschlagen
		 */
		failedTitle: () => LocalizedString
		/**
		 * {completedCount} von {totalCount} hochgeladen
		 */
		subtitleCompleted: (arg: { completedCount: number, totalCount: number }) => LocalizedString
		/**
		 * {completedCount} von {totalCount} hochgeladen, {failedCount} fehlgeschlagen
		 */
		subtitleWithFailures: (arg: { completedCount: number, failedCount: number, totalCount: number }) => LocalizedString
		/**
		 * Lade {count} Foto{{s}} hoch
		 */
		uploadingTitle: (arg: { count: number }) => LocalizedString
	}
	errors: {
		/**
		 * Du hast diese Challenge bereits abgeschlossen.
		 */
		challengeAlreadyCompleted: () => LocalizedString
		/**
		 * Diese Challenge ist voll. Wenn jemand sein Foto löscht, wird wieder ein Platz frei.
		 */
		challengeLocked: () => LocalizedString
		/**
		 * Die Challenge-Statistiken konnten nicht geladen werden.
		 */
		challengeStatsLoadFailed: () => LocalizedString
		/**
		 * Dieser Browser hat den Löschschlüssel für dieses Foto nicht mehr.
		 */
		deletePhotoNotAllowed: () => LocalizedString
		/**
		 * Die Fotodatei ist leer.
		 */
		emptyPhotoFile: () => LocalizedString
		/**
		 * Etwas ist schiefgelaufen.
		 */
		generic: () => LocalizedString
		/**
		 * Es können nur Bilder hochgeladen werden.
		 */
		imageUploadsOnly: () => LocalizedString
		/**
		 * Bitte wähle ein Foto aus.
		 */
		photoFileRequired: () => LocalizedString
		/**
		 * Das Foto konnte nicht gespeichert werden.
		 */
		photoStoreFailed: () => LocalizedString
		/**
		 * Die Anfrage konnte nicht abgeschlossen werden.
		 */
		requestFailed: () => LocalizedString
		/**
		 * Bitte gib deinen Namen an.
		 */
		uploadedByRequired: () => LocalizedString
		/**
		 * Die Anfrage konnte nicht deinem Benutzer zugeordnet werden.
		 */
		userIdRequired: () => LocalizedString
		/**
		 * Für Challenge-Uploads wird eine Benutzerkennung benötigt.
		 */
		userIdRequiredForChallengeUpload: () => LocalizedString
	}
}

export type Formatters = {}
